# Constants for Prompts
PROMPT_CUSTOMER_NAME = "Enter the customer name: "
PROMPT_EMAIL = "Enter the email: "
PROMPT_PASSWORD = "Enter the password: "
PROMPT_MOBILE = "Enter the mobile number: "
PROMPT_ACCOUNT_NO = "Enter the account number: "
PROMPT_CUSTOMER_ID = "Enter the Customer Id: "
PROMPT_NAME_TO_UPDATE = "Enter the name to update: "
PROMPT_EMAIL_TO_UPDATE = "Enter the email to update: "
PROMPT_PASSWORD_TO_UPDATE = "Enter the password to update: "
PROMPT_MOBILE_TO_UPDATE = "Enter the mobile number to update: "
PROMPT_CHOICE = "Enter your choice:"
PROMPT_ROLE = "Choose the Role:"
PROMPT_ADMIN_NAME = "Enter the name:"
PROMPT_ADMIN_EMAIL = "Enter the email:"
PROMPT_ADMIN_PASSWORD = "Enter the password:"
PROMPT_SEARCH_NAME = "Enter the name to search:"
PROMPT_SEARCH_CUSTOMER_ID = "Enter the customer Id:"
