ADD_CUSTOMER = "Enter 1 to Create Customer: "
SEARCH_RESTAURANT = "Enter 2 to Search Restaurant by Name or Food: "
PLACE_ORDER = "Enter 4 Place Order: "
CANCEL_ORDER = "Enter 5 Cancel Order: "
SHOW_MY_ORDER = "Enter 6 Show My Orders: "